version: '2'
services:
    keybox-app:
        image: keybox
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://keybox-mysql:3306/keybox?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    keybox-mysql:
        extends:
            file: mysql.yml
            service: keybox-mysql
